version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "[%(levelname)s] %(filename)s:%(lineno)s - %(message)s"
  full:
    format: "%(asctime)s [%(levelname)s] %(filename)s:%(lineno)s (P%(process)d:%(threadName)s) %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  info_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: full
    level: INFO
    filename: app.log
    when: midnight
    interval: 1
    encoding: utf-8
  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: full
    level: ERROR
    filename: error.log
    when: midnight
    interval: 1
    encoding: utf-8

logger:
  default:
    level: DEBUG
    handlers: [console, info_file, error_file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, info_file, error_file]